### PR TITLE
Update readme some more

### PR DESCRIPTION
**Pull request by ConnorRigby**
Lots of people blindly trying to compile on various internet websites. Hopefully alleviate it a little.

### CODE REVIEW

**Comment by natinusala** [comment]
I made a quick guide on GBATemp, hopefully that'll address some of the issues people have.

**Comment by ConnorRigby** [comment]
@natinusala That is good, but i think it should certainly be in the readme for those who don't visit GBATemp (including myself)

**Comment by natinusala** [comment]
I agree with that, the README is _just_ enough to make it work. It lacks extra steps

**Comment by ConnorRigby** [comment]
Whoops forgot to rebase.

**Pull request closed without merging**
